"""add drafts table

Revision ID: b93f6a38cc87
Revises: e11483a7ca30
Create Date: 2026-08-09 17:40:53.570928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b93f6a38cc87'
down_revision: Union[str, None] = 'e11483a7ca30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drafts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drafts')
    # ### end Alembic commands ###
