"""add reason_tag to mistake_notes

Revision ID: e11483a7ca30
Revises: aaf1f33b3324
Create Date: 2026-08-03 22:25:25.397248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e11483a7ca30'
down_revision: Union[str, None] = 'aaf1f33b3324'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mistake_notes', sa.Column('reason_tag', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mistake_notes', 'reason_tag')
    # ### end Alembic commands ###
